import { ReactCompareSlider, ReactCompareSliderImage } from "react-compare-slider";

interface Props {
  cbctSrc: string;
  sctSrc: string;
}

export default function ImageComparison({ cbctSrc, sctSrc }: Props) {
  return (
    <div className="not-prose comparison-shell">
      <div className="comparison-header">
        <div>
          <p className="comparison-kicker">Interactive result</p>
          <h3>CBCT → synthetic CT</h3>
        </div>
        <p className="comparison-help">Drag the divider to compare the same axial slice.</p>
      </div>
      <div className="comparison-stage">
        <ReactCompareSlider
          position={50}
          itemOne={
            <div className="comparison-image-wrap">
              <ReactCompareSliderImage src={cbctSrc} alt="Input CBCT axial slice" />
              <span className="comparison-label comparison-label-left">CBCT input</span>
            </div>
          }
          itemTwo={
            <div className="comparison-image-wrap">
              <ReactCompareSliderImage src={sctSrc} alt="EPC-3D-Diff synthetic CT axial slice" />
              <span className="comparison-label comparison-label-right">EPC-3D-Diff sCT</span>
            </div>
          }
          style={{ width: "100%", aspectRatio: "1 / 1", borderRadius: "1rem", overflow: "hidden" }}
        />
      </div>
      <p className="comparison-caption">
        Qualitative comparison of the CBCT input and the corresponding synthetic CT generated by EPC-3D-Diff.
      </p>
    </div>
  );
}
