import { useState } from "react";
import { ReactCompareSlider, ReactCompareSliderImage } from "react-compare-slider";

interface Props {
  ctSrc: string;
  cbctSrc: string;
  sctSrc: string;
}

export default function ImageComparison({ ctSrc, cbctSrc, sctSrc }: Props) {
  const [ctAvailable, setCtAvailable] = useState(true);

  return (
    <div className="not-prose comparison-shell comparison-shell-compact">
      <div className="comparison-header">
        <div>
          <p className="comparison-kicker">Interactive result</p>
          <h3>Reference CT and CBCT → synthetic CT</h3>
        </div>
        <p className="comparison-help">
          Reference CT is fixed on the left. Drag the divider on the right to
          compare the input CBCT with the EPC-3D-Diff sCT. 
        </p>
      </div>

      <div className="result-comparison-grid">
        <div className="reference-ct-card">
          <div className="comparison-image-wrap">
            {ctAvailable ? (
              <img
                src={ctSrc}
                alt="Reference CT axial slice"
                className="reference-ct-image"
                loading="lazy"
                onError={() => setCtAvailable(false)}
              />
            ) : (
              <div className="reference-ct-placeholder">
                <strong>Reference CT</strong>
                <span>Add the paired CT image as</span>
                <code>public/results/ct_237.png</code>
              </div>
            )}
            <span className="comparison-label comparison-label-left">
              <span>Reference CT</span>
              <span>PSNR (dB) / SSIM</span>
            </span>
          </div>
        </div>

        <div className="comparison-stage comparison-stage-small">
          <ReactCompareSlider
            position={50}
            itemOne={
              <div className="comparison-image-wrap">
                <ReactCompareSliderImage
                  src={cbctSrc}
                  alt="EPC-3D-Diff synthetic CT axial slice"
                />
                <span className="comparison-label comparison-label-left">
                  <span>CBCT input</span> 
                  <span>14.68 / 0.25</span>
                </span>
              </div>
            }
            itemTwo={
              <div className="comparison-image-wrap">
                <ReactCompareSliderImage
                  src={sctSrc}
                  alt="Input CBCT axial slice"
                />
                <span className="comparison-label comparison-label-right">
                  <span>EPC-3D-Diff sCT</span>
                  <span>43.12 / 0.99</span>
                </span>
              </div>
            }
            style={{
              width: "100%",
              aspectRatio: "1 / 1",
              borderRadius: "1rem",
              overflow: "hidden",
            }}
          />
        </div>
      </div>

      <p className="comparison-caption">
        Left: paired reference CT. Right: interactive comparison between the
        input CBCT and the corresponding synthetic CT generated by EPC-3D-Diff.
      </p>
    </div>
  );
}
